version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=jobradar
      - POSTGRES_PASSWORD=jobradar_password
      - POSTGRES_DB=jobradar
    ports:
      - "5432:5432"

volumes:
  postgres_data:
