"""Add AI features and location tracking

Revision ID: 80b97c6bcb60
Revises: 
Create Date: 2026-02-21 21:31:09.334882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b97c6bcb60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('employer_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('employer_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('experience_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'experience_years')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('employer_profiles', 'longitude')
    op.drop_column('employer_profiles', 'latitude')
    op.drop_column('applications', 'match_score')
    # ### end Alembic commands ###
